### PR TITLE
Make node id configurable

### PR DESCRIPTION
**Pull request by Nirothipan**
Fixes https://github.com/wso2/micro-integrator/issues/1223

## Purpose

Make the node id configurable.

**Toml config**
```toml
[cluster_config]
node_id = "node-1"
```

### CODE REVIEW

**Comment by Vathsan** [comment]
Do we support configuring node id as following in toml file?

```
[cluster_config]
node_id = "$env{variable_name}"
```
and
```
[cluster_config]
node_id = "$sys{property_name}"
```

**Comment by Nirothipan** [comment]
> Do we support configuring node id as following in toml file?
> 
> ```
> [cluster_config]
> node_id = "$env{variable_name}"
> ```
> 
> and
> 
> ```
> [cluster_config]
> node_id = "$sys{property_name}"
> ```

Yes and this is upto the parser to to resolve the sys or env and provide the values to the runtime as it does for other variables and this has nothing to do here. Here we are reading from the toml only.

**Comment by Vathsan** [comment]
> > Do we support configuring node id as following in toml file?
> > ```
> > [cluster_config]
> > node_id = "$env{variable_name}"
> > ```
> > 
> > 
> > and
> > ```
> > [cluster_config]
> > node_id = "$sys{property_name}"
> > ```
> 
> Yes and this is upto the parser to to resolve the sys or env and provide the values to the runtime as it does for other variables and this has nothing to do here. Here we are reading from the toml only.

Yes, by default the parser resolves the above two configurations. As per the fix in [1] we can set `avoidResolvingEnvAndSysVariable` system property and avoid resolving environment variables and system properties.  In occasions where we pass the above system properties, we need to handle resolving node_id from the code level. WDYT?
[1] https://github.com/wso2/config-mapper/pull/13
[2] https://github.com/wso2/config-mapper/pull/14

**Comment by Nirothipan** [comment]
> > > Do we support configuring node id as following in toml file?
> > > ```
> > > [cluster_config]
> > > node_id = "$env{variable_name}"
> > > ```
> > > 
> > > 
> > > and
> > > ```
> > > [cluster_config]
> > > node_id = "$sys{property_name}"
> > > ```
> > 
> > 
> > Yes and this is upto the parser to to resolve the sys or env and provide the values to the runtime as it does for other variables and this has nothing to do here. Here we are reading from the toml only.
> 
> Yes, by default the parser resolves the above two configurations. As per the fix in [1] we can set `avoidResolvingEnvAndSysVariable` system property and avoid resolving environment variables and system properties. In occasions where we pass the above system properties, we need to handle resolving node_id from the code level. WDYT?
> [1] [wso2/config-mapper#13](https://github.com/wso2/config-mapper/pull/13)

In the implementation we first check from system and then from env and then from toml ( using prop **nodeId** ). If the user has defined in toml as "$env" sthng has added the above mentioned property which is a contracting , then it is a user error. We can't cater that as we already have other options for them to defined node id as sys or env value.

**Pull request merged**
