### PR TITLE
Template message builder/formatter for text/html Content-Type

### PR DESCRIPTION
**Pull request by sajinieKavindya**
## Purpose
Template the following message builder and formatter for text/html Content-Type.

- msg builder - "org.wso2.carbon.relay.BinaryRelayBuilder"
- msg formatter - "org.wso2.carbon.relay.ExpandingMessageFormatter"

### CODE REVIEW

**Comment by Nirothipan** [comment]
@sajinieKavindya  seems there are some constant test failures with this change. can you please check .

**Comment by sdkottegoda** [comment]
Let's add the configs commented out to the deployment.toml rather than adding them to the default.json

**Comment by sachithKay** [comment]
Closing as per the new PR: https://github.com/wso2/micro-integrator/pull/1709

**Comment by sachithKay** [comment]
Related PR: https://github.com/wso2/micro-integrator/pull/1689

**Comment by Nirothipan** [comment]
This is failing since when the Accept header is set to text/html and the ESB responds with text/xml. In test clients, it sets the accept header by default to text/tml

**Pull request closed without merging**
